# Generated by Django 3.2.7 on 2021-10-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nalog',
            name='inn',
            field=models.CharField(default='000000000000', max_length=12),
        ),
        migrations.AddField(
            model_name='nalog',
            name='ogrn',
            field=models.CharField(default='0000000000000', max_length=13),
        ),
    ]
